config/routes.rb
Rails.application.routes.draw do
  get 'notes/new'
  post '/notes' => 'notes#create'
  get '/notes' => 'notes#index'
  get '/notes/:id' => "notes#show", as: 'note'

  root 'home#top'
  get 'about' => 'home#about'

  

end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @message = "ようこそGatebookへ！"
  end
  
  def about
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def new
  end

  def create
    @note = Note.new
    @note.title = params[:title]
    @note.content = params[:content]
    @note.save
    redirect_to note_path(@note.id)
  end

  def index
    @notes = Note.all
  end

  def show
    @note = Note.find(params[:id])
  end

  def edit
    @note = Note.find(params[:id])
  end

  # updateアクションを追加してください




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/home/about.html.erb
<!-- header部分をapplication.html.erbに移動し、about.html.erbから削除してください -->
<!-- header部分 -->
<header class="navbar">
  <div class="container">
    <div id="logo">Gatebook</div>
    <nav>
      <ul class="header-right">
        <li><%= link_to "Top", root_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </div>
</header>
<!-- header部分 -->

<!-- containerクラスのついたdivタグをapplication.html.erbに移動し、削除してください -->
<div class="container">
  <h1>Gatebookとは？</h1>
  <p>GatebookとはRuby on Railsというフレームワークを駆使した、<br>記事投稿SNSサービスです。<br>近況やつぶやきを投稿し、サービス上の友達と楽しくコミュニケーションできます。</p>
</div>

<!-- footer部分をapplication.html.erbに移動し、about.html.erbから削除してください -->
<!-- footer部分 -->
<div class="container">
  <footer class="footer">
    <small>
      &copy; 2015 Progate, Inc.
    </small>
  </footer>
</div>
<!-- footer部分 -->

app/views/home/top.html.erb
<header class="navbar">
  <div class="container">
    <div id="logo">Gatebook</div>
    <nav>
      <ul class="header-right">
        <li>Top</li>
        <li>About</li>
      </ul>
    </nav>
  </div>
</header>

<div class="container">
  <!-- 「Gatebookへようこそ」の部分を変数@messageに書き換えてHTMLに出力されるようにしてください -->
  <h1>ようこそGatebookへ！</h1>
</div>

<div class="container">
  <footer class="footer">
    <small>
      &copy; 2015 Progate, Inc.
    </small>
  </footer>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gatebook | 記事投稿SNSサービス</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <header class="navbar">
    <div class="container">
      <div id="logo">Gatebook</div>
      <nav>
        <ul class="header-right">
          <li><%= link_to "Top", root_path %></li>
          <li><%= link_to "About", about_path %></li>
        </ul>
      </nav>
    </div>
  </header>

  <div class="container">
    <%= yield %>
  </div>

  <div class="container">
    <footer class="footer">
      <small>
        &copy; 2015 Progate, Inc.
      </small>
    </footer>
  </div>

</body>
</html>

app/views/notes/create.html.erb
<p><%= @note.title %></p>
<p><%= @note.content %></p>

app/views/notes/edit.html.erb
<h1>投稿を編集する</h1>
<%= form_tag update_note_path(@note.id), method: 'patch' do %>
  タイトル
  <%= text_field_tag :title, @note.title, class: "form-control title-field" %>
  内容
  <%= text_area_tag :content, @note.content, class: "form-control content-field" %>
  <%= submit_tag "保存", class: "btn primary-btn" %>
<% end %>

app/views/notes/index.html.erb
<h1>投稿の一覧</h1>
<ul class="notes">
  <% @notes.each do |note| %>
    <li>
      <p>タイトル</p>
      <span class="content">
        <%= link_to note.title, show_note_path(note.id) %>
      </span>
    </li>
  <% end %>
</ul>

app/views/notes/new.html.erb
<h1>新規投稿する</h1>
<%= form_tag notes_path do %>
  タイトル
  <input type="text" name="title" class="form-control title-field">
  内容
  <textarea name="content" class="form-control content-field"></textarea>
  <input type="submit" value="投稿する" class="btn primary-btn">
<% end %>

app/views/notes/show.html.erb
<h2>タイトル</h2>
<p><%= @note.title %></p>
<h2>内容</h2>
<p><%= @note.content %></p>

<%= link_to "編集", edit_note_path(@note.id), class: "btn edit-btn" %>
<!-- 削除のリンクを追加してください -->